language: node_js
node_js:
  - node

env:
  global:
    - CC_TEST_REPORTER_ID=1803d262472cfd5468d13181c2f71c7bacf02196959469df6269606aeecb8264
    
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-cover

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT